#!/bin/bash
apt-get update && apt-get upgrade -y
apt-get install curl -y
apt-get install apache2 -y
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y
apt-get install libapache2-mod-php php-mcrypt php-mysql php-mbstring php-curl php-tokenizer php-xml

service apache2 restart
apt-get install mysql-server php5-mysql -y
mysql_install_db
mysql_secure_installation
apt-get install phpmyadmin -y
php5enmod mcrypt
service apache2 restart
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
apt-get install libssh2-1-dev libssh2-php -y
mysql -u root
php -m |grep ssh2
service apache2 restart
# Changed webserver root directory
apt install sed
sed -i 's/var\/www/var\/www\/html\/sshpanel\/public/g' /etc/apache2/apache2.conf

cd /var/www/html
apt install git -y

# Cloning!
git clone git://github.com/xiao3vv/xiao3vpn.git

rm index.html
clear
